name = "order-discount-zig"
type = "order_discounts"
api_version = "2023-01"

[build]
command = "bash build.sh"
path = "zig-out/bin/order-discount-zig-optimized.wasm"

[ui.paths]
create = "/discount/:functionId/new"
details = "/discount/:functionId/:id"

[input.variables]
namespace = "$app:polyglot-functions"
key = "function-configuration"
