// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA0a30a08DecodeMainApi(in *jlexer.Lexer, out *DiscountConfiguration) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "discountPercentage":
			out.DiscountPercentage = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA0a30a08EncodeMainApi(out *jwriter.Writer, in DiscountConfiguration) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"discountPercentage\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.DiscountPercentage))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DiscountConfiguration) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonA0a30a08EncodeMainApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DiscountConfiguration) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA0a30a08EncodeMainApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DiscountConfiguration) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonA0a30a08DecodeMainApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DiscountConfiguration) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA0a30a08DecodeMainApi(l, v)
}
