name = "order-discount-assemblyscript"
type = "order_discounts"
api_version = "2022-07"

[build]
command = "npm run asbuild:release"
path = "build/release.wasm"

[ui.paths]
create = "/discount/:functionId/new"
details = "/discount/:functionId/:id"

[input.variables]
namespace = "$app:polyglot-functions"
key = "function-configuration"