[package]
name = "order-discount-rust"
version = "1.0.0"
edition = "2021"

[dependencies]
shopify_function = "0.2.5"
serde = { version = "1.0.13", features = ["derive"] }
serde_with = "1.13.0"
serde_json = "1.0"
graphql_client = "0.13.0"

[profile.release]
lto = true
opt-level = 'z'
strip = true
