name = "volume-discount"
type = "product_discounts"
api_version = "2022-07"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/volume-discount.wasm"

[ui.paths]
create = "/discount/:functionId/new"
details = "/discount/:functionId/:id"
