name = "order-discount-golang"
type = "order_discounts"
api_version = "2022-07"

[build]
command = "bash build.sh"
path = "build/order-discount-golang.wasm"

[ui.paths]
create = "/discount/:functionId/new"
details = "/discount/:functionId/:id"
